'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MehtaT_ChuiW_VasudeoJ_FinalProject.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anthonydavis_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anthonydavis_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anthonydavis_playerselected1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anthonydavis_playerselected1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anthonydavisimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anthonydavisimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anthonydavisimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anthonydavisimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anthonydavisimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anthonydavisimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anthonydavisimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anthonydavisimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property anthonydavisimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anthonydavisimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property basketballnets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("basketballnets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blakegriffin_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blakegriffin_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blakegriffin_playerselected1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blakegriffin_playerselected1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blakegriffindunk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blakegriffindunk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blakegriffinimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blakegriffinimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blakegriffinimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blakegriffinimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blakegriffinimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blakegriffinimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blakegriffinimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blakegriffinimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blakegriffinimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blakegriffinimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boban() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boban", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boogiecousins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boogiecousins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrispaul_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrispaul_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrispaul_playerselected1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrispaul_playerselected1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrispaulimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrispaulimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrispaulimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrispaulimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrispaulimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrispaulimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrispaulimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrispaulimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chrispaulimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chrispaulimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property curryshot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curryshot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarcuscousins_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarcuscousins_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarcuscousins_playerselected1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarcuscousins_playerselected1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarcuscousinsimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarcuscousinsimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarcuscousinsimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarcuscousinsimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarcuscousinsimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarcuscousinsimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarcuscousinsimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarcuscousinsimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demarcuscousinsimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demarcuscousinsimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dfox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property donovanactuallydunks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donovanactuallydunks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property donovandunk_dunkcalc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donovandunk_dunkcalc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property donovandunk_dunkcalc1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donovandunk_dunkcalc1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property donovandunk_dunkcalc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donovandunk_dunkcalc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property donovandunk3_dunkcalc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donovandunk3_dunkcalc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dotloadingicon_loadingscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dotloadingicon_loadingscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draymondgreen_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draymondgreen_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draymondgreen_playerselected1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draymondgreen_playerselected1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draymondgreenimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draymondgreenimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draymondgreenimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draymondgreenimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draymondgreenimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draymondgreenimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draymondgreenimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draymondgreenimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property draymondgreenimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("draymondgreenimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dunkCalculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dunkCalculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exitbuttonimag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exitbuttonimag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property exitbuttonimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exitbuttonimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property finalproject_loadingscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finalproject_loadingscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greywheel_loadingscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greywheel_loadingscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gswchampionship() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gswchampionship", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hardenmad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hardenmad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jamesharden_playerseleted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jamesharden_playerseleted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jamesharden_playerseleted1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jamesharden_playerseleted1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jameshardenimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jameshardenimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jameshardenimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jameshardenimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jameshardenimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jameshardenimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jameshardenimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jameshardenimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jameshardenimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jameshardenimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jimmybutler_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jimmybutler_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jimmybutler_playerselected1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jimmybutler_playerselected1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jimmybutlerimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jimmybutlerimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jimmybutlerimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jimmybutlerimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jimmybutlerimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jimmybutlerimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jimmybutlerimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jimmybutlerimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jimmybutlerimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jimmybutlerimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property joelembiidtrashtalk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joelembiidtrashtalk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jrueholiday_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jrueholiday_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jrueholidayimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jrueholidayimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jrueholidayimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jrueholidayimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jrueholidayimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jrueholidayimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jrueholidayimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jrueholidayimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jrueholidayimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jrueholidayimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property karlanthonytownsimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karlanthonytownsimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property karlanthonytownsimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karlanthonytownsimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property karlanthonytownsimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karlanthonytownsimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property karlanthonytownsimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karlanthonytownsimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property karlanthonytownsimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karlanthonytownsimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property karltowns_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("karltowns_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kawhileonard_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kawhileonard_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kawhileonardimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kawhileonardimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kawhileonardimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kawhileonardimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kawhileonardimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kawhileonardimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kawhileonardimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kawhileonardimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kawhileonardimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kawhileonardimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kawhiraptors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kawhiraptors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kdclutch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kdclutch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kevindurant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kevindurant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kevindurant_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kevindurant_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kevindurantimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kevindurantimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kevindurantimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kevindurantimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kevindurantimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kevindurantimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kevindurantimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kevindurantimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kevindurantimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kevindurantimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property klaythompson_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("klaythompson_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property klaythompsonimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("klaythompsonimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property klaythompsonimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("klaythompsonimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property klaythompsonimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("klaythompsonimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property klaythompsonimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("klaythompsonimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property klaythompsonimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("klaythompsonimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property knicksbench() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("knicksbench", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property kobebryant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kobebryant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lebronjames() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lebronjames", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lebronjames_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lebronjames_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lebronjamesimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lebronjamesimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lebronjamesimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lebronjamesimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lebronjamesimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lebronjamesimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lebronjamesimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lebronjamesimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lebronjamesimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lebronjamesimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lebronjamesmissesdunk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lebronjamesmissesdunk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property liquidloadingicon_loadingscreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("liquidloadingicon_loadingscreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MJ() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MJ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nikolajokic_playersselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nikolajokic_playersselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nikolajokicimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nikolajokicimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nikolajokicimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nikolajokicimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nikolajokicimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nikolajokicimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nikolajokicimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nikolajokicimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nikolajokicimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nikolajokicimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stephcurry_playerselected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stephcurry_playerselected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stephencurryimage1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stephencurryimage1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stephencurryimage2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stephencurryimage2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stephencurryimage3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stephencurryimage3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stephencurryimage4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stephencurryimage4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property stephencurryimage5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stephencurryimage5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TallMen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TallMen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
